-- Limpa base
USE pesquisapsicologia;

DELETE FROM VALUEANSWER
WHERE IDVALUEANSWER > -1;

DELETE FROM ANSWER
WHERE IDANSWER > -1;

DELETE FROM SURVEY
WHERE IDSURVEY > -1;

DELETE FROM PERSON
WHERE IDPERSON > -1;
